"use client";

import Breadcrumb from "@/components/Breadcrumb";
import { BlockMath, InlineMath } from "react-katex";
import "katex/dist/katex.min.css";

const problemColors = [
  // Original Variations
  "from-red-100 to-rose-200 dark:from-red-800 dark:to-rose-700",
  "from-orange-100 to-amber-200 dark:from-orange-800 dark:to-amber-700",
  "from-yellow-100 to-lime-200 dark:from-yellow-800 dark:to-lime-700",
  "from-green-100 to-emerald-200 dark:from-green-800 dark:to-emerald-700",
  "from-teal-100 to-cyan-200 dark:from-teal-800 dark:to-cyan-700",
  "from-sky-100 to-blue-200 dark:from-sky-800 dark:to-blue-700",
  "from-indigo-100 to-violet-200 dark:from-indigo-800 dark:to-violet-700",
  "from-purple-100 to-fuchsia-200 dark:from-purple-800 dark:to-fuchsia-700",
  "from-pink-100 to-rose-200 dark:from-pink-800 dark:to-rose-700",
  "from-gray-100 to-slate-200 dark:from-gray-800 dark:to-slate-700",

  // Red/Pink Variations
  "from-red-200 to-pink-300 dark:from-red-700 dark:to-pink-600",
  "from-rose-100 to-red-200 dark:from-rose-700 dark:to-red-800",
  "from-red-50 to-rose-100 dark:from-red-900 dark:to-rose-800",

  // Orange/Yellow Variations
  "from-orange-200 to-yellow-300 dark:from-orange-700 dark:to-yellow-600",
  "from-amber-100 to-orange-200 dark:from-amber-700 dark:to-orange-800",
  "from-yellow-50 to-amber-100 dark:from-yellow-900 dark:to-amber-800",

  // Green/Teal Variations
  "from-green-200 to-teal-300 dark:from-green-700 dark:to-teal-600",
  "from-emerald-100 to-green-200 dark:from-emerald-700 dark:to-green-800",
  "from-green-50 to-emerald-100 dark:from-green-900 dark:to-emerald-800",

  // Blue/Sky Variations
  "from-blue-200 to-sky-300 dark:from-blue-700 dark:to-sky-600",
  "from-sky-200 to-blue-300 dark:from-sky-700 dark:to-blue-600",
  "from-sky-50 to-blue-100 dark:from-sky-900 dark:to-blue-800",

  // Purple Variations
  "from-purple-200 to-indigo-300 dark:from-purple-700 dark:to-indigo-600",
  "from-violet-100 to-purple-200 dark:from-violet-700 dark:to-purple-800",
  "from-purple-50 to-violet-100 dark:from-purple-900 dark:to-violet-800",

  // Gray Variations
  "from-gray-200 to-slate-300 dark:from-gray-700 dark:to-slate-600",
  "from-slate-200 to-gray-300 dark:from-slate-700 dark:to-gray-600",
  "from-gray-50 to-slate-100 dark:from-gray-900 dark:to-slate-800",

  // Complementary/Contrasting Options
  "from-blue-200 to-yellow-200 dark:from-blue-700 dark:to-yellow-700",
  "from-pink-200 to-teal-200 dark:from-pink-700 dark:to-teal-700",
  "from-green-200 to-red-200 dark:from-green-700 dark:to-red-700",

  // Neutral with Subtle Variation
  "from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800",
  "from-zinc-50 to-zinc-100 dark:from-zinc-900 dark:to-zinc-800",
  "from-stone-50 to-stone-100 dark:from-stone-900 dark:to-stone-800",
];

export default function Magnetostatics() {
  const breadcrumbItems = [
    { label: "Physics", href: "/physics" },
    {
      label: "Concepts",
      href: "/physics/",
    },
    {
      label: "Electromagnetism",
      href: "/physics/concepts/electromagnetism",
    },
    {
      label: "Magnetostatics",
      href: "/physics/concepts/electromagnetism/magnetostatics",
    },
  ];

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Hero Section */}
      <div className="mb-12 space-y-6 text-center">
        <h1 className="bg-gradient-to-r from-indigo-700 to-purple-800 bg-clip-text text-4xl font-bold text-transparent sm:text-5xl md:text-6xl dark:from-indigo-200 dark:to-purple-300">
          Magnetostatics
        </h1>
        <p className="mx-auto max-w-2xl text-lg text-gray-600 md:text-xl dark:text-gray-300">
          Explore the fascinating world of magnetic fields created by steady
          currents and delve into the fundamental principles governing magnetic
          interactions.
        </p>
      </div>

      <Breadcrumb items={breadcrumbItems} />

      {/* Main Content Sections */}
      <div className="mt-12 space-y-8">
        {/* Introduction to Magnetostatics */}
        <div className="rounded-2xl bg-gradient-to-br from-sky-200 to-blue-200 p-6 dark:from-sky-600 dark:to-blue-600">
          <h2 className="bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-2xl font-semibold text-transparent dark:from-blue-300 dark:to-purple-300">
            Introduction to Magnetostatics
          </h2>
          <div className="mt-4">
            <p className="text-gray-700 dark:text-gray-300">
              Magnetostatics is the study of magnetic fields generated by steady
              currents. It deals with the forces, fields, and materials
              associated with static magnetic fields. This section covers the
              fundamental principles of magnetostatics, including the
              Biot-Savart Law, Ampère’s Law, magnetic flux, and magnetic
              materials.
            </p>
          </div>
        </div>

        {/* Biot-Savart Law */}
        <div className="rounded-2xl bg-gradient-to-br from-teal-200 to-emerald-200 p-6 dark:from-teal-600 dark:to-emerald-600">
          <h2 className="bg-gradient-to-r from-teal-600 to-cyan-600 bg-clip-text text-2xl font-semibold text-transparent dark:from-teal-300 dark:to-cyan-300">
            Biot-Savart Law
          </h2>
          <div className="mt-4">
            <p className="text-gray-700 dark:text-gray-300">
              The Biot-Savart Law describes the magnetic field generated by a
              steady current. It is the magnetostatic equivalent of
              Coulomb&#39;s Law in electrostatics.
            </p>
          </div>
          <div className="mt-4 grid gap-6 md:grid-cols-2">
            <div className="space-y-4">
              <div className="rounded-lg bg-black/5 p-4 backdrop-blur-sm dark:bg-black/20">
                <h3 className="text-lg font-semibold text-indigo-600 dark:text-indigo-300">
                  Biot-Savart Law Formula
                </h3>
                <BlockMath math="d\mathbf{B} = \frac{\mu_0}{4\pi} \frac{I \, d\mathbf{l} \times \hat{r}}{r^2}" />
                <p className="mt-2 text-gray-600 dark:text-gray-300">
                  The magnetic field <InlineMath math="d\mathbf{B}" /> due to a
                  small current element <InlineMath math="I \, d\mathbf{l}" />{" "}
                  is proportional to the current and inversely proportional to
                  the square of the distance.
                  <br />
                  Where:
                  <br />
                  <InlineMath math="d\mathbf{B}" /> = Magnetic field (Teslas)
                  <br />
                  <InlineMath math="\mu_0" /> = Permeability of free space (4π ×
                  10⁻⁷ H/m)
                  <br />
                  <InlineMath math="I" /> = Current (Amperes)
                  <br />
                  <InlineMath math="d\mathbf{l}" /> = Length element of the
                  current (m)
                  <br />
                  <InlineMath math="\hat{r}" /> = Unit vector from the current
                  element to the point of observation
                  <br />
                  <InlineMath math="r" /> = Distance from the current element to
                  the point of observation (m)
                </p>
              </div>
            </div>
            <div className="space-y-4">
              <div className="rounded-lg bg-black/5 p-4 backdrop-blur-sm dark:bg-black/20">
                <h3 className="text-lg font-semibold text-emerald-600 dark:text-emerald-300">
                  Applications
                </h3>
                <p className="mt-2 text-gray-600 dark:text-gray-300">
                  The Biot-Savart Law is used to calculate the magnetic field
                  due to current-carrying wires, loops, and other geometries.
                </p>
              </div>
            </div>
          </div>
          {/* Illustration: Biot-Savart Law */}
          <div className="mt-6 flex justify-center">
            <svg viewBox="0 0 200 100" className="w-full max-w-md">
              <path d="M20 50 L180 50" stroke="currentColor" strokeWidth="2" />
              <circle cx="100" cy="50" r="5" fill="#3b82f6" />
              <text x="90" y="30" fontSize="12" fill="#3b82f6">
                I dl
              </text>
              <text x="150" y="50" fontSize="12" fill="currentColor">
                dB
              </text>
            </svg>
          </div>
        </div>

        {/* Ampère’s Law */}
        <div className="rounded-2xl bg-gradient-to-br from-purple-200 to-pink-200 p-6 dark:from-purple-600 dark:to-pink-600">
          <h2 className="bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-2xl font-semibold text-transparent dark:from-purple-300 dark:to-pink-300">
            Ampère’s Law
          </h2>
          <div className="mt-4">
            <p className="text-gray-700 dark:text-gray-300">
              Ampère’s Law relates the magnetic field around a closed loop to
              the current passing through the loop. It is one of Maxwell&#39;s
              equations and is particularly useful for calculating magnetic
              fields in symmetric systems.
            </p>
          </div>
          <div className="mt-4 grid gap-6 md:grid-cols-2">
            <div className="space-y-4">
              <div className="rounded-lg bg-black/5 p-4 backdrop-blur-sm dark:bg-black/20">
                <h3 className="text-lg font-semibold text-indigo-600 dark:text-indigo-300">
                  Ampère’s Law Formula
                </h3>
                <BlockMath math="\oint \mathbf{B} \cdot d\mathbf{l} = \mu_0 I_{\text{enc}}" />
                <p className="mt-2 text-gray-600 dark:text-gray-300">
                  The line integral of the magnetic field around a closed loop
                  is proportional to the current enclosed by the loop.
                  <br />
                  Where:
                  <br />
                  <InlineMath math="\mathbf{B}" /> = Magnetic field (Teslas)
                  <br />
                  <InlineMath math="d\mathbf{l}" /> = Differential length vector
                  (m)
                  <br />
                  <InlineMath math="\mu_0" /> = Permeability of free space (4π ×
                  10⁻⁷ H/m)
                  <br />
                  <InlineMath math="I_{\text{enc}}" /> = Enclosed current
                  (Amperes)
                </p>
              </div>
            </div>
            <div className="space-y-4">
              <div className="rounded-lg bg-black/5 p-4 backdrop-blur-sm dark:bg-black/20">
                <h3 className="text-lg font-semibold text-emerald-600 dark:text-emerald-300">
                  Applications
                </h3>
                <p className="mt-2 text-gray-600 dark:text-gray-300">
                  Ampère’s Law is particularly useful for calculating magnetic
                  fields in systems with high symmetry, such as infinite wires,
                  solenoids, and toroids.
                </p>
              </div>
            </div>
          </div>
          {/* Illustration: Ampère’s Law */}
          <div className="mt-6 flex justify-center">
            <svg viewBox="0 0 200 100" className="w-full max-w-md">
              <circle
                cx="100"
                cy="50"
                r="40"
                fill="none"
                stroke="#3b82f6"
                strokeWidth="2"
              />
              <circle cx="100" cy="50" r="10" fill="#10b981" />
              <text x="90" y="30" fontSize="12" fill="#3b82f6">
                Amperian Loop
              </text>
              <text x="90" y="70" fontSize="12" fill="#10b981">
                I_enc
              </text>
            </svg>
          </div>
        </div>

        {/* Magnetic Flux & Gauss’s Law for Magnetism */}
        <div className="rounded-2xl bg-gradient-to-br from-rose-200 to-orange-200 p-6 dark:from-rose-600 dark:to-orange-600">
          <h2 className="bg-gradient-to-r from-rose-600 to-orange-600 bg-clip-text text-2xl font-semibold text-transparent dark:from-rose-300 dark:to-orange-300">
            Magnetic Flux & Gauss’s Law for Magnetism
          </h2>
          <div className="mt-4">
            <p className="text-gray-700 dark:text-gray-300">
              Magnetic flux is a measure of the total magnetic field passing
              through a given area. Gauss’s Law for Magnetism states that the
              net magnetic flux through any closed surface is zero, implying
              there are no magnetic monopoles.
            </p>
          </div>
          <div className="mt-4 grid gap-6 md:grid-cols-2">
            <div className="space-y-4">
              <div className="rounded-lg bg-black/5 p-4 backdrop-blur-sm dark:bg-black/20">
                <h3 className="text-lg font-semibold text-indigo-600 dark:text-indigo-300">
                  Magnetic Flux
                </h3>
                <BlockMath math="\Phi_B = \int \mathbf{B} \cdot d\mathbf{A}" />
                <p className="mt-2 text-gray-600 dark:text-gray-300">
                  Magnetic flux is the integral of the magnetic field over a
                  surface area.
                  <br />
                  Where:
                  <br />
                  <InlineMath math="\Phi_B" /> = Magnetic flux (Webers)
                  <br />
                  <InlineMath math="\mathbf{B}" /> = Magnetic field (Teslas)
                  <br />
                  <InlineMath math="d\mathbf{A}" /> = Differential area vector
                  (m²)
                </p>
              </div>
            </div>
            <div className="space-y-4">
              <div className="rounded-lg bg-black/5 p-4 backdrop-blur-sm dark:bg-black/20">
                <h3 className="text-lg font-semibold text-emerald-600 dark:text-emerald-300">
                  Gauss’s Law for Magnetism
                </h3>
                <BlockMath math="\oiint \mathbf{B} \cdot d\mathbf{A} = 0" />
                <p className="mt-2 text-gray-600 dark:text-gray-300">
                  The net magnetic flux through any closed surface is zero,
                  indicating that magnetic field lines are continuous and there
                  are no magnetic monopoles.
                </p>
              </div>
            </div>
          </div>
          {/* Illustration: Magnetic Flux */}
          <div className="mt-6 flex justify-center">
            <svg viewBox="0 0 200 100" className="w-full max-w-md">
              <rect
                x="50"
                y="20"
                width="100"
                height="60"
                fill="none"
                stroke="#3b82f6"
                strokeWidth="2"
              />
              <text x="90" y="50" fontSize="12" fill="#3b82f6">
                Φ_B = ∫ B · dA
              </text>
            </svg>
          </div>
        </div>

        {/* Magnetic Materials */}
        <div className="rounded-2xl bg-gradient-to-br from-amber-200 to-yellow-200 p-6 dark:from-amber-600 dark:to-yellow-600">
          <h2 className="bg-gradient-to-r from-amber-600 to-yellow-600 bg-clip-text text-2xl font-semibold text-transparent dark:from-amber-300 dark:to-yellow-300">
            Magnetic Materials
          </h2>
          <div className="mt-4">
            <p className="text-gray-700 dark:text-gray-300">
              Magnetic materials are classified based on their response to
              external magnetic fields. They include diamagnetic, paramagnetic,
              and ferromagnetic materials.
            </p>
          </div>
          <div className="mt-4 grid gap-6 md:grid-cols-2">
            <div className="space-y-4">
              <div className="rounded-lg bg-black/5 p-4 backdrop-blur-sm dark:bg-black/20">
                <h3 className="text-lg font-semibold text-indigo-600 dark:text-indigo-300">
                  Types of Magnetic Materials
                </h3>
                <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300">
                  <li>
                    <strong>Diamagnetic</strong>: Weakly repelled by magnetic
                    fields.
                  </li>
                  <li>
                    <strong>Paramagnetic</strong>: Weakly attracted by magnetic
                    fields.
                  </li>
                  <li>
                    <strong>Ferromagnetic</strong>: Strongly attracted by
                    magnetic fields and can retain magnetization.
                  </li>
                </ul>
              </div>
            </div>
            <div className="space-y-4">
              <div className="rounded-lg bg-black/5 p-4 backdrop-blur-sm dark:bg-black/20">
                <h3 className="text-lg font-semibold text-emerald-600 dark:text-emerald-300">
                  Magnetic Permeability
                </h3>
                <BlockMath math="\mu = \mu_0 (1 + \chi)" />
                <p className="mt-2 text-gray-600 dark:text-gray-300">
                  The magnetic permeability of a material describes how easily
                  it can be magnetized.
                  <br />
                  Where:
                  <br />
                  <InlineMath math="\mu" /> = Permeability of the material (H/m)
                  <br />
                  <InlineMath math="\mu_0" /> = Permeability of free space (4π ×
                  10⁻⁷ H/m)
                  <br />
                  <InlineMath math="\chi" /> = Magnetic susceptibility
                </p>
              </div>
            </div>
          </div>
          {/* Illustration: Magnetic Materials */}
          <div className="mt-6 flex justify-center">
            <svg viewBox="0 0 200 100" className="w-full max-w-md">
              <rect
                x="50"
                y="20"
                width="100"
                height="60"
                fill="none"
                stroke="#3b82f6"
                strokeWidth="2"
              />
              <text x="90" y="50" fontSize="12" fill="#3b82f6">
                Magnetic Materials
              </text>
            </svg>
          </div>
        </div>

        {/* Numerical Problems Section */}
        <div className="mt-16">
          <div className="rounded-2xl bg-gradient-to-br from-gray-200 to-indigo-200 p-6 dark:from-gray-800 dark:to-indigo-800">
            <h2 className="bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-2xl font-semibold text-transparent dark:from-blue-300 dark:to-purple-300">
              Numerical Problems
            </h2>
            <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {[
                {
                  problem:
                    "A long straight wire carries a current of 10 A. Calculate the magnetic field at a distance of 0.05 m from the wire.",
                  solution:
                    "B = \\frac{\\mu_0 I}{2\\pi r} = \\frac{4\\pi \\times 10^{-7} \\times 10}{2\\pi \\times 0.05} = 4 \\times 10^{-5} \\ \\text{T}",
                },
                {
                  problem:
                    "A circular loop of wire with a radius of 0.1 m carries a current of 5 A. Calculate the magnetic field at the center of the loop.",
                  solution:
                    "B = \\frac{\\mu_0 I}{2r} = \\frac{4\\pi \\times 10^{-7} \\times 5}{2 \\times 0.1} = 3.14 \\times 10^{-5} \\ \\text{T}",
                },
                {
                  problem:
                    "A solenoid with 500 turns per meter carries a current of 2 A. Calculate the magnetic field inside the solenoid.",
                  solution:
                    "B = \\mu_0 n I = 4\\pi \\times 10^{-7} \\times 500 \\times 2 = 1.26 \\times 10^{-3} \\ \\text{T}",
                },
                {
                  problem:
                    "A square loop of side 0.2 m carries a current of 3 A. Calculate the magnetic field at the center of the square.",
                  solution:
                    "B = \\frac{2\\sqrt{2} \\mu_0 I}{\\pi a} = \\frac{2\\sqrt{2} \\times 4\\pi \\times 10^{-7} \\times 3}{\\pi \\times 0.2} = 1.7 \\times 10^{-5} \\ \\text{T}",
                },
                {
                  problem:
                    "Calculate the magnetic flux through a circular loop of radius 0.1 m placed in a uniform magnetic field of 0.5 T, with the loop's plane perpendicular to the field.",
                  solution:
                    "\\Phi_B = BA = 0.5 \\times \\pi (0.1)^2 = 0.0157 \\ \\text{Wb}",
                },
                {
                  problem:
                    "A toroid has 1000 turns and carries a current of 1 A. If its mean radius is 0.1 m, calculate the magnetic field inside the toroid.",
                  solution:
                    "B = \\frac{\\mu_0 N I}{2\\pi r} = \\frac{4\\pi \\times 10^{-7} \\times 1000 \\times 1}{2\\pi \\times 0.1} = 2 \\times 10^{-3} \\ \\text{T}",
                },
                {
                  problem:
                    "A wire carrying a current of 5 A is placed in a uniform magnetic field of 0.2 T. If the length of the wire in the field is 0.5 m and it is perpendicular to the field, calculate the force on the wire.",
                  solution:
                    "F = BIL = 0.2 \\times 5 \\times 0.5 = 0.5 \\ \\text{N}",
                },
                {
                  problem:
                    "An electron moves at a speed of 2 × 10⁶ m/s perpendicular to a magnetic field of 0.1 T. Calculate the magnetic force on the electron.",
                  solution:
                    "F = qvB = 1.6 \\times 10^{-19} \\times 2 \\times 10^6 \\times 0.1 = 3.2 \\times 10^{-14} \\ \\text{N}",
                },
                {
                  problem:
                    "A rectangular loop of dimensions 0.1 m × 0.2 m carries a current of 2 A. Calculate the magnetic moment of the loop.",
                  solution:
                    "m = NIA = 1 \\times 2 \\times (0.1 \\times 0.2) = 0.04 \\ \\text{A} \\cdot \\text{m}^2",
                },
                {
                  problem:
                    "A solenoid of length 0.5 m has 2000 turns and carries a current of 4 A. Calculate the magnetic field at the center of the solenoid.",
                  solution:
                    "B = \\mu_0 n I = 4\\pi \\times 10^{-7} \\times \\frac{2000}{0.5} \\times 4 = 2.01 \\times 10^{-2} \\ \\text{T}",
                },
              ].map((item, index) => (
                <div
                  key={index}
                  className={`rounded-lg border bg-gradient-to-br p-4 dark:border-gray-700 ${
                    problemColors[index % problemColors.length]
                  }`}
                >
                  <div className="flex items-start justify-between">
                    <span className="text-sm text-gray-700 dark:text-gray-300">
                      Problem {index + 1}
                    </span>
                  </div>
                  <div className="mt-2 text-sm text-gray-600 dark:text-gray-400">
                    <p>{item.problem}</p>
                  </div>
                  <details className="group mt-2">
                    <summary className="cursor-pointer text-sm font-medium text-indigo-600 dark:text-blue-300">
                      Show Solution
                    </summary>
                    <div className="mt-2 whitespace-pre-wrap text-sm text-gray-600 group-open:block dark:text-gray-400">
                      <p>
                        <BlockMath>{item.solution}</BlockMath>
                      </p>
                    </div>
                  </details>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Decorative Section Divider */}
      <div className="mt-16 flex items-center justify-center space-x-4">
        <div className="h-px flex-1 bg-gradient-to-r from-transparent via-gray-600 to-transparent dark:via-gray-400" />
        <span className="text-sm italic text-gray-500 dark:text-gray-200">
          Unveiling the Invisible Forces
        </span>
        <div className="h-px flex-1 bg-gradient-to-r from-transparent via-gray-600 to-transparent dark:via-gray-400" />
      </div>
    </div>
  );
}
